version: '3.8'

services:
  rest-service:
    container_name: rest-service
    build:
      context: .
      dockerfile: Dockerfile
    image: h3nnessey/rest-service
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    command: npm run start:dev
    volumes:
      - ./src:/app/src
      - logs:/app/logs
    networks:
      - service_network
    restart: always

  postgres:
    container_name: postgres
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    image: h3nnessey/postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_DB}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - 'postgres:/var/lib/postgresql/data/'
      - 'postgres_logs:/var/log/postgresql/'
    networks:
      - service_network
    command: postgres -c logging_collector=on -p ${DATABASE_PORT}
    restart: always

networks:
  service_network:
    name: rest_service_bridge
    driver: bridge

volumes:
  postgres:
    name: postgres
  postgres_logs:
    name: postgres_logs
  logs:
    name: logs
