version: '3.8'

services:
  rest-service:
    container_name: rest-service
    build:
      context: .
      dockerfile: Dockerfile
    image: h3nnessey/rest-service
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    command: npm run start:dev
    volumes:
      - ./src:/app/src
      - /app/node_modules
    restart: unless-stopped
  postgres:
    container_name: postgres
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    image: h3nnessey/postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_DB}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - 'postgres:/var/lib/postgresql/data/'
      - 'logs:/var/log/postgresql/'
    command: -p ${DATABASE_PORT}
    restart: unless-stopped
volumes:
  postgres: {}
  logs: {}
